package com.leevinapp.testingdemo

data class GithubResponse(
    val authorizations_url: String?,
    val code_search_url: String?,
    val commit_search_url: String?,
    val current_user_authorizations_html_url: String?,
    val current_user_repositories_url: String?,
    val current_user_url: String?,
    val emails_url: String?,
    val emojis_url: String?,
    val events_url: String?,
    val feeds_url: String?,
    val followers_url: String?,
    val following_url: String?,
    val gists_url: String?,
    val hub_url: String?,
    val issue_search_url: String?,
    val issues_url: String?,
    val keys_url: String?,
    val label_search_url: String?,
    val notifications_url: String?,
    val organization_repositories_url: String?,
    val organization_teams_url: String?,
    val organization_url: String?,
    val public_gists_url: String?,
    val rate_limit_url: String?,
    val repository_search_url: String?,
    val repository_url: String?,
    val starred_gists_url: String?,
    val starred_url: String?,
    val user_organizations_url: String?,
    val user_repositories_url: String?,
    val user_search_url: String?,
    val user_url: String?
)